### ISSUE TITLE
Give each question a ID to allow linking to specific questions.

### ISSUE THREAD

**Issue by derpmarine168** [30-seconds/30-seconds-of-interviews#114]
what it says in the title! this has already been implemented in 30 seconds of css, and would be extremely useful, for example to link a friend to a specific question without them having to find it manually.

**Comment by skatcat31** [comment]
The readme does have these, however the generated site does not. It might not be to hard to implement, however the question becomes "what is a unique id we can use" since questions are long, and snippet names are kind of long too. Still a great suggestion.

It looks like it can be put into the build script pretty easily and just based on the snippet name. Then we just merely need to add an anchor to the beginning of each snippet box, and a link that can easily be copied to the header question.

This implementation will cause breaks in links if the snippet file name changes, but that shouldn't be happening anyways.

This should be easy enough. Thanks for the suggestion!

**Comment by fejes713** [comment]
@derpmarine168 took me much more than a weekend to find time to add one line of code. This is solved now in #129 and should be live very soon. Thanks for recommending this! 👍
