### ISSUE TITLE
The answer of the question "In which states can a Promise be?" have to include the state <settled> 

### ISSUE THREAD

**Issue by Fziliotti** [30-seconds/30-seconds-of-interviews#131]

**Comment by skatcat31** [comment]
`settled` is not a valid state for a promise.

It is a colloquial way of referring to a non-pending promise without knowledge of it's actual state. It is not in the specification nor can the state be reached since a promise is considered `settled` as a quantum(either `resolved` or `rejected`), and quantum are not a possible state in JS.

While we understand the intent of this issue it is an incorrect interpretation.

**Comment by skatcat31** [comment]
[Promise specification for possible states](https://promisesaplus.com/#promise-states)
